version: 2

jobs:
  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y libsnappy-dev openjdk-8-jre-headless
            pip install tox
      - run:  
          name: Run tests
          command: tox

workflows:
  version: 2
  build:
    jobs:
      - test
